name: tf_data_streamer
description: This provides you with a streamer of data, which you can listen to. Useful when you want to listen to the changes in certain data, coming from a source e.g., API, Files, or from somewhere within the code and has probability of changes with time, or requires reloading after certain events. Provides useful data to alter data, filter data, add errors to the stream.
version: 1.0.0
homepage: https://github.com/rahul-badgujar/tf_data_streamer_dart_package.git

environment:
  sdk: ">=2.15.1 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
